In [2]:
import numpy as np

In [3]:
arr =np.random.rand(3,4)
arr

array([[0.62772072, 0.73261809, 0.35013399, 0.1835973 ],
       [0.45066186, 0.92407974, 0.87924442, 0.17465559],
       [0.26007116, 0.15485113, 0.92392887, 0.65615935]])

In [9]:
print(arr.T)
print()
#or
print("best")
print(np.transpose(arr))
print()
#or
print(arr.transpose())


[[0.62772072 0.45066186 0.26007116]
 [0.73261809 0.92407974 0.15485113]
 [0.35013399 0.87924442 0.92392887]
 [0.1835973  0.17465559 0.65615935]]

best
[[0.62772072 0.45066186 0.26007116]
 [0.73261809 0.92407974 0.15485113]
 [0.35013399 0.87924442 0.92392887]
 [0.1835973  0.17465559 0.65615935]]

[[0.62772072 0.45066186 0.26007116]
 [0.73261809 0.92407974 0.15485113]
 [0.35013399 0.87924442 0.92392887]
 [0.1835973  0.17465559 0.65615935]]


In [12]:
arr1 = ("romisaa",("mahmoud"),("naira"),("malak"),("ahmed"),("mohamed"),("hala"))
print(arr1)

('romisaa', 'mahmoud', 'naira', 'malak', 'ahmed', 'mohamed', 'hala')


In [13]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

print("-------------------------")
arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
-------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [15]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [16]:
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [19]:
arr.reshape((2,6))

array([[0.62772072, 0.73261809, 0.35013399, 0.1835973 , 0.45066186,
        0.92407974],
       [0.87924442, 0.17465559, 0.26007116, 0.15485113, 0.92392887,
        0.65615935]])

In [20]:
arr.resize((2,6))

In [21]:
new = arr.flatten()
new.ndim # number of dimensions

1

In [25]:
arr = np.array([1,2,3])

In [26]:
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [27]:
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [28]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [29]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [8,2,6])    
print(arr3)

[8 2 6 1 2 3]


In [30]:
newarr = np.array([1,3,4])
newarr = np.insert(newarr,0, 5)
newarr

array([5, 1, 3, 4])

In [31]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]
